var n;Array.prototype.Mb||(Array.prototype.Mb=function(a){0>a&&(a+=this.length);return this[a]});Array.prototype.includes||(Array.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);
const aa=Boolean,u=Object.isExtensible,x=RegExp.prototype.test,ba=RegExp.prototype.exec,ca=Array.isArray,da=Array.from,ea=Array.prototype.includes;Array.prototype.concat.bind([]);const y=Math.floor,z=Math.random,fa=Function.call.bind(Array.prototype.slice),ha=Function.apply.bind(Array.prototype.push),ia=Function.apply.bind(String.fromCharCode,null),C="undefined"==typeof browser;C&&(browser=chrome);
const D=navigator.userAgent.includes("Edge/"),ja=navigator.userAgent.includes("Edg/"),F=navigator.userAgent.includes("Firefox/"),ka=navigator.userAgent.includes("OPR/"),la=navigator.userAgent.includes("YaBrowser/");var G=0,ma,na,oa,ra,sa;const H="undefined"==typeof globalThis?this:globalThis,ta=F?69:D?77:66,ua=F?220:150,I=browser.runtime.getManifest();var va=I.permissions.includes("notifications")||null;
const wa={16:"images/logo16.png",32:"images/logo32.png"},xa={16:"images/logo16x.png",32:"images/logo32x.png"},ya=["127.0.0.1:1001","0.1.0.1:1001"],za=/(?!)/,Aa=["main_frame","sub_frame"],Ba=["object","image"];var J=Ba.concat("xmlhttprequest",D?"other":[]),Ca=Aa.concat(Ba,"xmlhttprequest","other");
const L=["*://*/*"],Da=["ftp://*/*"],Ea=L.concat(Da,"file:///*",C?"about:blank":[]),Fa=L.concat(C?"about:blank":[]),Ga=C&&btoa(z().toString().substr(2,9)),Ha=browser.runtime.getURL("captured.html?"+(Ga?"auth="+Ga+"&":"")),Ia=browser.runtime.getURL("welcome.html?"+(Ga?"auth="+Ga+"&":"")),Ja=browser.runtime.getURL("").slice(0,-1),Ka=location.href,La=ka||la,Ma=C||D,Na=!F;var Oa=C;
const Pa=x.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|ms-appx-web|moz-extension):/),Qa=x.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i),Ra=x.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|plain))$/),Sa=x.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),Ta=x.bind(/^(MPD|M3U8|F4M)$/i),Ua=x.bind(/^ftp:|^idmreg:|\bidman|\binternetdownloadmanager\b/i),Va=x.bind(/^[GPTSDVACRHX]*$/),Wa=ba.bind(/^(.*?)(,\s*)?\bapplication\/vnd\.t1c\.([^\s,]+)(?:,\s*)?(.*)$/);
ba.bind(/:\/\/.+\/([^/]+?(?:\.([^./]+?))?)(?=[?#]|$)/);
const Xa=ba.bind(/\.([^.\\/]*?)(?:\.[0-9.]+)?$/),Ya=ba.bind(/^v(\d+)\.(\d+)(?:b(\d+))?\b/),Za=ea.bind([301,302,303,307,308]),$a=ea.bind([301,302,303]),ab=/[:,;]/,bb=/[,;]/,cb=x.bind(/messaging host not found|no such native application|application is not installed/i),db=x.bind(/^(?:https?|socks[45])$/),eb={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},fb=[],gb={"-1":[2,[111,112],[111]],1:[2,[115,116,117,124,118,119,120,121,127,131,132,123,125,126,129,130],[115,111,112,113,114]],2:[2,
[114,113,113,115,116,117,118,122,119,125,126,124,121,120,123,112],[111,112,114]],3:[null,[113,114,115,116,117],[112]],4:[2,[111,101,113,112,114,118,119,124,115,116,117,120,121,122,123],[111]],5:[null,[111,112,113],[111]],6:[null,[],[111]]},hb={16:1,17:2,18:4,45:8,46:16},ib={http:1,https:9,ftp:2,ftps:10,idmreg:12,idmdwnlmfv3:33,idmdwnlmfv4:33,idmdwnlmfv5:33},jb={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT",
"text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/json+protobuf":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/ocsp-response":"OCSP","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/pkix-crl":"CRL","application/torrent":"TORRENT|BTT",
"application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2","application/vnd.apple.mpegurl":"M3U8","application/vnd.yt-ump":"UMP","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-chrome-extension":"CRX","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ",
"application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP",
"video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8","video/mp4":"MP4|M4V|M4S","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI",
"audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4|M4S","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG",
"image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
function kb(a,b,c,d,e,f,h,k){if(a){var g=["MSG#",a,"#",b,"#",c,"#",d];this.f=a;this.type=b;this.m=c;this.flags=d;this.a=e||[];this.h=g;this.v=h;this.s=k;if(e)for(var l of e)g.push(":",l||0);if(f)for(var m in f)if(parseInt(m)&&(a=void 0,b=f[m],null!=b&&!this.g))switch(c=this.h,d=this.v,h=this.s,e=d&&h,h=h?"/":":",k=b instanceof String?"string":typeof b,c.push(",",m,"="),k){case "string":c.push(lb(b),":",b);break;case "number":c.push(b);break;case "boolean":c.push(b?1:0);break;case "object":if(b instanceof
Array){k=c.length;l=g=0;for(a of b)a instanceof ArrayBuffer||a instanceof Uint8Array?(d?(a=mb(a),g+=a.length):g+=a.byteLength,++l):(a=a.toString(),g+=lb(a)),c.push(a);l&&e?(b=btoa(c.splice(k).join("")),c.push(b.length,"%",b)):c.splice(k,0,g,l?h:":")}else b instanceof ArrayBuffer||b instanceof Uint8Array?e?(b=btoa(mb(b)),c.push(b.length,"%",b)):d?(b=mb(b),c.push(b.length,":",b)):c.push(b.byteLength,h,b):b instanceof Blob&&c.push(b.size,h,b)}}else this.l=new FileReader}
function nb(){this.a=nb.prototype.h++}nb.prototype.h=1;function ob(a,b,c,d){this.id=a;this.port=b;c&&(this.b=c=c.toLowerCase(),this.ha="iframe"==c);d&&(this.c=d)}ob.prototype.a=0;function pb(a,b,c){this.id=b+","+a;this.B=0==a;this.c=null==c||0>c?null:b+","+c}function qb(){}function rb(a){a.g||(a.h.push(";"),a.g=!0);return a.h.join("")}function sb(a){a.g||(a.h.push(";"),a.g=!0);return new Blob(a.h)}function tb(a,b,c){a.g?a.b(a):(b.a=c||0,b.b=0,a.l.onload=a.o.bind(a,b),ub(a,b,0,50))}
kb.prototype.o=function(a){for(var b=this.l.result;;)switch(a.b){case 0:var c=b.search(ab);if(0>=c)return this.b(this);var d=b[c],e=b.slice(0,c++).split("#",6);if(5!=e.length||"MSG"!=e[0])return this.b(this);this.f=parseInt(e[1]);this.type=parseInt(e[2]);this.m=parseInt(e[3]);this.flags=parseInt(e[4]);b=b.slice(c);a.a+=c;a.b=":"==d?1:","==d?2:5;break;case 1:c=b.search(bb);if(0>=c)return c?ub(this,a,b.length,100):this.b(this);d=b[c];e=this.a=b.slice(0,c++).split(":");for(var f=0;f<e.length;f++){var h=
e[f];e[f]=h.includes(".")?parseFloat(h):parseInt(h)}b=b.slice(c);a.a+=c;a.b=","==d?2:5;break;case 2:c=b.search(ab);if(0>=c)return c?ub(this,a,b.length,25):this.b(this);d=b[c];e=b.slice(0,c++).split("=",3);if(2!=e.length)return this.b(this);f=parseInt(e[0]);e=parseInt(e[1]);a.a+=c;if(":"==d){a.f=f;a.c=e;a.b=3;b=a.c;c=a.a;a=a.slice(c,c+b);a.size==b?this.l.readAsText(a):this.b(this);return}this[f]=e;b=b.slice(c);a.b=","==d?2:5;break;case 3:return this[a.f]=b,a.a+=a.c,a.b=4,ub(this,a,0,21);case 4:switch(b[0]){case ",":a.b=
2;b=b.slice(1);break;case ";":a.b=5;break;default:return this.b(this)}a.a++;break;case 5:this.g=!0;this.i(this);a.size>a.a&&(b=new kb,b.i=this.i,b.b=this.b,tb(b,a,a.a));return}};function ub(a,b,c,d){var e=b.a;c=e+c;b.size>c?a.l.readAsBinaryString(b.slice(e,c+d)):a.b(a)}
function M(){var a=this.constructor.prototype,b;for(b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.l=0;this.H=null;this.da=this.Aa=0;this.rb=1;this.D=null;this.Va=I.version||"";this.Gb="";this.oa=0;this.xa=!1;this.I=null;this.Ba=!1;this.P=this.v=null;this.ib=this.ub=this.Ka=this.o=!1;this.N=!F;this.Hb=this.jb=!0;this.nb=this.J=this.K=null;this.Fb=this.wa=this.ya=!1;this.qb=!0;this.Zc=this.Oc=1;this.Oa=this.m=this.la=null;this.Ra=1;this.Ib=0;this.ca=this.V=this.Ua=null;
this.ob=za;this.ea=[];this.Na=0;this.pb=null;this.Ta=this.Ma=!1;this.ma=this.s=null;this.Ca=Array(16);this.c={};this.h={};this.a={};this.G={};this.b={};this.pa={};this.g={};this.f={};this.za={};this.ua={};this.i={};this.na={};this.va={};this.va.Jc=[];this.eb=[];browser.browserAction&&(vb(this,!1),browser.browserAction.onClicked.addListener(this.Wb));F&&1056964608<=G&&browser.contextMenus.onShown.addListener(this.Xb);F&&browser.runtime.onInstalled.addListener(this.ac);browser.runtime.onMessage.addListener(this.bc);
browser.windows.onCreated.addListener(this.Bb);browser.windows.onRemoved.addListener(this.Cb);browser.windows.onFocusChanged.addListener(this.Ec);browser.windows.onBoundsChanged&&browser.windows.onBoundsChanged.addListener(this.Dc);browser.tabs.onActivated.addListener(this.tc);browser.tabs.onUpdated.addListener(this.wc);browser.tabs.onRemoved.addListener(this.vc);browser.tabs.onAttached&&browser.tabs.onAttached.addListener(this.uc);C&&1056964608<=G&&browser.webRequest.onBeforeRequest.addListener(this.Yb,
{urls:[browser.runtime.getURL("*")]},["blocking"]);this.Kc();this.Kb()}function wb(){}wb.prototype=[];var N=wb.prototype;wb=null;n=M.prototype;n.Xb=function(a,b){b&&xb(this,b.id,!0,!1,!0)};n.ac=function(a){this.Va=a.version=I.version;this.Nc=a};function yb(a,b){b&&browser.storage.local.set({consent:a.Va});a.J=null;a.Pa(5);a.N=!0;zb(a)}n.bc=function(a,b){switch(a[0]){case 38:a[1]&&this.xa&&browser.storage.local.set({silent:!0});browser.tabs.remove(b.tab.id);break;case 42:yb(this,!0);break;case 43:browser.management.uninstallSelf({showConfirmDialog:!0})}};
n.Wb=function(a){if(this.Fb){if(this.J)return browser.windows.update(this.J,{focused:!0});var b=a.id,c=this.i[b];vb(this,c,b,!0);this.wa&&(c?(this.ba(a.windowId),Ab(this,b)):Bb(this,b))}};function vb(a,b,c,d){c?a.i[c]=!b:a.Fb=b||d;Cb(b,c,d)}
function Cb(a,b,c){if(c||!b||!a){var d=a;F&&!b&&(a||c?browser.browserAction.enable():browser.browserAction.disable(),d=!0);c=a?Db+Eb:b?Fb+Eb:c?Fb:Gb;var e=d?wa:xa,f=F&&b&&989855744<=G;if(D||C&&822083584>G)e=e[16];D||browser.browserAction.setTitle({title:a&&f?null:c,tabId:b});browser.browserAction.setIcon({path:d&&f?null:e,tabId:b});a||browser.browserAction.setBadgeBackgroundColor({color:"#606060"});browser.browserAction.setBadgeText({text:a?f?null:"":"X",tabId:b})}}
function zb(a){var b=a.c,c=a.na={};browser.contextMenus.removeAll();for(var d=0;d<Hb.length;d++){var e=Hb[d];e[0]&&b[e[1]]&&(c[d]=browser.contextMenus.create({title:Ib(e[2]),contexts:e[3].split(","),onclick:e[4].bind(a),documentUrlPatterns:e[5]||Ea,enabled:!0}))}a.wa||(a.wa=!0,vb(a,!0),a.A(1,browser.runtime.onConnect,a.oc),C&&a.A(1,browser.proxy.settings.onChange,a.zb),C&&browser.proxy.settings.get({},a.zb),a.A(1,browser.webNavigation.onCreatedNavigationTarget,a.mc),a.A(1,browser.webNavigation.onCommitted,
a.yb),a.A(1,browser.webNavigation.onHistoryStateUpdated,a.dc),(b=a.c[17])&&a.A(2,browser.webRequest.onBeforeRequest,a.xc,{urls:b.split("|"),types:Aa},["blocking"]),Jb(a,!0),browser.tabs.query({url:L},a.Da))}
function Jb(a,b){C&&a.o&&(browser.downloads.setUiOptions?browser.downloads.setUiOptions({enabled:!b}):browser.downloads.setShelfEnabled(!b));if(b){C&&a.o&&a.A(3,browser.downloads.onCreated,a.Zb);C&&a.o&&a.A(3,browser.downloads.onDeterminingFilename,a.$b);b=ra?void 0:Ca;const c=["blocking"],d=C&&!sa&&1207959552<=G?["extraHeaders"]:[];a.A(4,browser.webRequest.onBeforeRequest,a.Ab,{urls:Da,types:Aa},c);a.A(4,browser.webRequest.onBeforeRequest,a.Ab,{urls:L,types:b},["requestBody"]);a.A(4,browser.webRequest.onBeforeSendHeaders,
a.zc,{urls:L,types:b},["requestHeaders"].concat(c,d));a.A(4,browser.webRequest.onHeadersReceived,a.Bc,{urls:L,types:b},["responseHeaders"].concat(c));a.A(4,browser.webRequest.onResponseStarted,a.Cc,{urls:L,types:b});a.A(4,browser.webRequest.onErrorOccurred,a.Ac,{urls:L,types:b});F&&a.A(4,browser.webRequest.onBeforeRedirect,a.yc,{urls:L,types:Aa})}else a.Pa(3,4)}
n.zb=function(a){browser.runtime.lastError;if(a){var b=a.value;a=eb[b.mode];var c,d;this.Ca.fill(void 0);if(5==a&&(d=b.pacScript))d.data&&5E4<d.data.length?a=4:(c=d.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=d.url,this.Ca.fill(!0);else if(7==a){b=b.rules;d=b.bypassList;c=Kb(this,b.singleProxy);if(!c){c=Kb(this,b.fallbackProxy);var e=Kb(this,b.proxyForHttp,1),f=Kb(this,b.proxyForHttps,9);b=Kb(this,b.proxyForFtp,2);e!=f||e!=b||e!=c&&c?(c=(e||"")+";"+(f||
"")+";"+(b||"")+";"+(c||""),++a):c=e}d&&d.length&&(c+=";"+d.join(","))}b=5>a?a.toString():c?a+":"+c:null;b!=this.s&&(this.s&&this.gb(),this.s=b)}};function Kb(a,b,c){if(b){var d=b.scheme||"http",e="https"==d;a=a.Ca;c?a[c]=e:a.fill(e);if(db(d))return d+"://"+b.host+(b.port?":"+b.port:"")}}
function Lb(a,b,c,d){if(b){var e=b.type;if("direct"==e)return"0";"socks"==e&&(e="socks5");if(db(e)){var f="1:"+e+"://"+b.host+":"+b.port;"socks5"==e&&b.proxyDNS&&(f+="#");c||d||!(c=a.ma)||(c=c.substr(c.indexOf(";")+1||c.length));c&&(f+=";"+c);d&&f&&(a.ma=f);return f}}}
n.gb=N[N.length]=function Mb(a,b){if(void 0===a){if((Na||Oa)&&this.l){var d=this.V;d||(b="http://"+(1==this.l?(new URL(this.H.url)).host:ya[0]),d=b+"/status/204+IDM");a=new XMLHttpRequest;a.timeout=1E3;a.onreadystatechange=Mb.bind(this,a,b);a.open("GET",d,!0);a.send()}}else 4==a.readyState&&(204!=a.status?this.V=this.ca=null:b&&(this.V=b+"/status/204+IDM",this.ca=Na&&this.I?b+"/client/"+this.I:null))};n.La=function(a,b,c,d){var e=this.g;return b in e?e[b]:e[b]=new ob(b,a,c,d)};
function Nb(a,b){a=a.f;var c=b.id;a[c]!==b&&(a[c]=b,D&&(a[b.requestId]=b));F&&b.Ja&&(a[b.Ja]=b)}function Ob(a,b,c,d,e){if(u(b)){var f=b.frameId||0;var h=b.parentFrameId;var k=b.method&&b.id;c||(c=b.tabId);e||(e=b.url)}else f=b;var g=a.G[c+","+f];g||(g=new pb(f,c,h),a.G[g.id]=g);k?(g.f!=k&&(g.f=k,g.l=e,g.C=!1,g.b&&(g.b=e.startsWith(b.initiator||b.originUrl))),g.h="POST"==b.method):e&&(e.startsWith("about:blank")?f&&(g.b=!0):g.j=e);null!=d&&(g.refresh=d);return g}
function Pb(a,b){return a.G[b.tabId+","+b.frameId]}function Qb(a){var b=new nb;return a.pa[b.a]=b}function Rb(a,b){var c;b instanceof nb?c=b.a:b=a.pa[c=b];delete a.pa[c];return b}function Sb(a,b){for(var c of a.ea)if(c&&c[101].test(b))return c.O;return 0}
n.Qa=function(){var a=this.Aa%(ya.length+1);if(a<ya.length){a=ya[a];var b=this.I||0,c=z().toString().substr(2,9);a=this.H=new WebSocket("ws://"+a+"/?cid="+b+"&rnd="+c,"plugin.v3.internetdownloadmanager.com");a.onopen=this.Za;a.onclose=this.Y;a.onmessage=this.sc;a.onerror=O;1==a.readyState?this.Za(1):3==a.readyState?this.Y():this.D=H.setTimeout(this.Y,1500,a)}else D?this.Y():(a=this.H=browser.runtime.connectNative("com.tonec.idm"),a.onDisconnect.addListener(this.Y),a.onMessage.addListener(this.ec),
this.D=H.setTimeout(this.Za,0,2))};n.Za=function(a){this.D&&(H.clearTimeout(this.D),this.D=null);this.l=u(a)?1:a;this.rb=1;this.xa=!1;var b=browser.i18n.getUILanguage().replace("_","-");"sr"==b&&(b+="-Cyrl-CS");a=[105,76,La?1028:1031,0,16845059,this.I,0,I.manifest_version];b={[112]:na,[113]:ma,[125]:JSON.stringify(this.Nc),[116]:b};P(this,2,5,La?0:1024,a,b)};
n.Y=function(a){this.D&&(H.clearTimeout(this.D),this.D=null);var b=browser.runtime.lastError||a&&a.error,c=this.H;if(c instanceof WebSocket){if(a===c)return c.close()}else c&&cb(b&&b.message)&&(this.xa=!0);this.H=null;this.l&&(this.l=0,this.za={},Jb(this,!1),this.Pa(1,2),this.wa=!1,this.s=this.ca=this.V=null,vb(this,!1));a=++this.Aa;b=ya.length+1;c=a/b;120>c&&(1==c&&Tb(this),!a||a%b?this.Qa():H.setTimeout(this.Qa,5E3*c))};
n.wb=function(){var a=this.H;a instanceof WebSocket?a.close():a&&(a.disconnect(),this.Y())};n.sc=function(a){var b=new kb;b.i=this.xb;b.b=this.wb;tb(b,a.data)};n.ec=function(a){var b=new kb;b.i=this.xb;b.b=this.wb;tb(b,new Blob([a]))};
function P(a,b,c,d,e,f,h){var k=a.da,g=a.l;if(!g)return 0;1==b&&92>k&&4>e.length&&(e.length=4);var l=a.rb++;b=new kb(l,b,c,d,e,f,2==g,99<=k);if(h)return h.open("POST",a.ca+"?seq="+l,!1),h.send(sb(b)),200==h.status?l:0;if(1==g)a.H.send(sb(b));else try{a.H.postMessage(rb(b))}catch(m){return a.Y(),0}d&1&&(a.za[l]=b);return l}
function Wb(a,b){if(b.a){var c=b.a[1],d=a.f[c];if(d)return d.W?b.c=d.port.id:null;d=a.h;for(var e in d)if(d[e].c==c)return b.c=e}e=b[6];d=b[17];var f=b[50],h=b[7],k=a.va,g=a.g;a=a.a;var l;if((l=k[e])||(l=k[d]))return b.c=l.id;if(l=k[f])var m=l.id;for(c in g){k=g[c];var r=k.c;if(r){if(r==e||r==d||r==f){l=k.port;if(h){var q=a[l.tabId];q&&q.j!=h&&(l=null)}if(l)return b.c=l.id}if(r==h)var p=k.port.id}}return m?b.c=m:p?b.c=p:null}
n.Qb=N[N.length]=function Xb(a,b,c,d){var f;a:for(;!c;){if(f=a.c)return f;if(a.a){var h=this.a[a.a[6]+","+a.a[7]];h?f=h.id:(h=a.a[7])&&this.h[h]&&(f=h)}if(f||(f=Wb(this,a)))break;var k=this.h,g=a[50],l=a[7],m;for(m in k){h=k[m];if(h.j==g){f=m;break a}h.j==l&&(f=m)}if(f)break;return l?browser.tabs.query({url:l},Xb.bind(this,a,b,!0)):null}return c?(browser.runtime.lastError,d&&(d=d.shift())&&(h=this.a[d.id])&&(f=a.c=h.id),b&&b(f)):a.c=f};
n.kb=N[N.length]=function Yb(a,b,c){var e=a.tabId,f=a.R;if(b)if(ca(c))for(var h=a.j,k=h.includes("#")&&Zb(h),g=c.length;g--;){b=c[g];var l=b.frameId;if(l!=f)if(l&&!b.ad&&(b.url==h||k&&b.url==k))f=a.R=l;else continue;var m=b.parentFrameId;break}else c?m=c.parentFrameId:browser.runtime.lastError;else if(0<f?!a.b:null==f){if(f&&822083584<=G)return browser.webNavigation.getFrame({frameId:f,tabId:e},Yb.bind(this,a,!0));if(f||a.j)return browser.webNavigation.getAllFrames({tabId:e},Yb.bind(this,a,!0))}0<=
m&&(a.b=e+","+m);if(null!=f&&a.g){if(b=this.G[e+","+f])a.c=b.f,a.C|=b.C,a.refresh|=b.refresh,a.i=b.b,(c=b.Z)&&a.j!=c&&(a.Z=c),a.b||(a.b=b.c),(c=this.f[a.c])&&!c.port&&(c.port=a);this.a[e+","+f]=a;m=this.Ka?1:null;c=a.O;e=[11,this.da,a.id,e,f,c,a.refresh,a.C,m&&fb[m]];c&&a.C&&(f=this.ea[c],e.push(fb[f.Rb]),ha(e,f.Ob.map($b(f)).map(ac)));a.postMessage(e)}};
n.ka=N[N.length]=function bc(a,b,c,d,e,f,h,k){var l=cc(a);if(l){var m=0<(l&32),r=1==(l&=7);if(r&&!m&&!h)return Q(a,bc.bind(this,a,b,c,d,e,f,!0));h=[l];a={[6]:Zb(a,r,this),[50]:b,[7]:c,[8]:d,[100]:e,[102]:f,[51]:R(k),[54]:navigator.userAgent,[121]:F?this.ma:this.s};P(this,14,1,0,h,a)}};
n.Lc=N[N.length]=function dc(a,b,c,d,e,f){if(a&&a.length){if(c){var k=c.c;var g=c.V;var l=c.l}if(!d){if(!a||!a.length)return;f=ec();k&&!g&&Q(k,e=S());for(var m of a)Q(m[0],f[f.length]=S());return T(dc,this,a,b,c,!0,e,f)}e&&(g=R(e));for(m of a)m[5]=R(f.shift());b=0;c=[0,0,0];k={[8]:4,[54]:navigator.userAgent,[7]:k,[110]:l,[111]:g,[121]:F?this.ma:this.s};1<a.length&&(c[1]=P(this,15,1,0,[a.length],k),b=16,k={});for(m of a)c[2]++,k[6]=m[0],k[100]=m[2],k[102]=m[3],k[50]=m[4],k[51]=m[5],P(this,14,2,b,c,
k)}};
n.Sa=function(a,b){if(!this.l)return fc(b.id,"cannot_contact_idm");var c=a.linkUrl,d=a.pageUrl,e=d,f=this.a[b.id+","+a.frameId];if(a.menuItemId==this.na[4])return browser.downloads.search({query:[c]},this.Pb.bind(this,c));if(a.menuItemId==this.na[1]){if(c=a.frameUrl,c&&"about:blank"!=c||(c=d,e=null),this.v&&f&&f.O)return gc(this,!0)}else if(!c){c=a.srcUrl;if(!cc(c)){if(this.v&&f&&f.O&&"video"==a.mediaType)return gc(this,!0);return}if(f&&c)return a=Qb(this),a.tabId=b.id,a.port=f,a.i=c,a.m=e,a.c=d,
a.flags=4,f.postMessage([18,a.a,c])}c&&this.ka(c,e,d,4)};n.hb=function(a,b){if(!this.l)return fc(b.id,"cannot_contact_idm");xb(this,b.id,a.menuItemId==this.na[2])};n.Pb=function(a,b){for(var c,d,e;c=b.pop();)c.exists&&"complete"==c.state?d||e||(e=c.referrer):(d||(d=c.referrer),browser.downloads.erase({id:c.id}));this.ka(a,d||e,null,4)};
function xb(a,b,c,d,e,f,h,k,g){if(!d||a.c[-5]){var l=a.a[b];if(l){var m=Qb(a);m.tabId=b;m.port=l;m.G=c;m.I=e;m.b=0;m.f=[];if(l=d&&!!f)m.N=!0,m.P=f,m.s=h,m.v=k,m.o=g,f.B||hc(a,f);f=m.a;(d=d&&a.c[12])?(d=d.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"),d="^(?:http|https|ftp|ftps)://(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)"):d="^(?:http|https|ftp|ftps)://";m.g=ic(a,b,[12,f,c,l||e,d]);m.D=0;m.g||Rb(a,m)}}}
n.Gc=function(a,b,c,d,e,f,h,k){if(a=this.pa[b]){d&&(a.b+=d);h&&(a.c=h);k&&(a.l=k);if(e&&("string"==typeof e&&(e=JSON.parse(e)),e instanceof Array)){if(f)for(var g of e)g[4]=f;ha(a.f,e)}++a.D<a.g||(a.N?(d=a.tabId,(e=this.b[a.port.a])&&e.u==d&&a.b&&(f=a.o,h=e.b,k=e.a,P(this,10,1,0,[4294967295,e.m,Math.round(a.s*f+(e.h+h)*k),Math.round(a.v*f+(e.G+h)*k),0,a.b]),this.m=d,ic(this,d,[13,!0]))):a.I?(d=0<a.b,this.qb!=d&&(this.qb=d,browser.contextMenus.update(this.na[2],{visible:d}),browser.contextMenus.refresh())):
(d=a.f,d.length?this.Lc(d,a.G,a):fc(a.tabId,"cannot_find_links")),Rb(this,a))}};n.kc=function(a,b,c,d){(a=Rb(this,b))&&this.ka(a.i,a.m,a.c,a.flags,c,d)};n.Zb=function(a){(this.o||a.byExtensionId)&&!this.Ta&&this.c[-6]&&cc(a.finalUrl||a.url,!0)&&(this.ua[a.id]=a,browser.downloads.pause(a.id,O))};
n.$b=function(a,b){var c=a.id,d=this.ua;if(!d[c])return!1;var e=this.c,f=a.finalUrl||(a.finalUrl=a.url),h=new URL(f),k=a.U=cc(f,!0),g=a.sa=jc(a.filename||h.pathname);if(!(a.fa=this.Ma)&&!this.o&&(!e[1].test(g)||e[9].test(h.hostname)||e[19].test(h.href)))return kc(this,c);a.Mc=b;d[c]=a;if(1==k){if(!a.referrer){b=this.b;for(var l of V(this.h))if(l.j==f&&(a.referrer=l.m,(c=b[l.a])&&c.u==l.tabId))break}var m;Q(f,l=S());f!=a.url&&Q(a.url,m=S());T(this.tb,this,a,l,m);return a.lb=!0}return this.tb(a)};
n.tb=function(a,b,c){var d=Date.parse(a.startTime)||Date.now();d=[a.id,0,y(d),0,a.U,2];b={[6]:Zb(a.finalUrl,!0),[4]:a.sa,[103]:a.totalBytes||null,[100]:a.filename||null,[127]:a.mime||null,[8]:a.fa?2048:0,[50]:a.referrer||null,[51]:R(b),[54]:navigator.userAgent,[122]:this.s};a.finalUrl!=a.url&&(b[17]=Zb(a.url),b[56]=R(c));return!!P(this,13,1,129,d,b)||kc(this,a.id)};
function kc(a,b,c){var d=a.ua[b];if(d){delete a.ua[b];if(c)return browser.downloads.cancel(b,O),!0;d.lb&&(d.lb=!1,d.Mc());browser.downloads.resume(b,O)}return!1}n.nc=function(a,b,c,d,e,f){this.La(a,b,c,d);P(this,23,2,0,[b,a.tabId,a.c,a.O,a.R],{[132]:d,[133]:e,[134]:f})};
n.X=N[N.length]=function lc(a,b,c){if(4294967295==a)this.m=null,c=!0;else{var e=this.g[a];if(e){c=e.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:e.a=3;H.setTimeout(lc.bind(this),1E3,a,!1,!0);return}e.a=0;c=!0}}c&&P(this,8,1,32,[a])};
n.Tc=function(a,b,c,d,e,f,h,k,g,l){var m=a.tabId,r=a.a,q=this.b[r],p=this.i[m];if(b){var w=Rb(this,b);if(w=w&&w.H){if(!c&&a.i){var t=this.a[a.b];if(t)return t.postMessage([15,b,null,w[6],w[17],w[50],w[31],w[133],w[134]])}var v,A;b={};if(!d){if(!c||null==e){if(!a.B){c=a.qa;f="iframe";h=a.j;var B=!!c}if(!B){c=m;f=h=null;var K=!0}}a=this.La(a,c,f,h);q=m==q.u&&!q.L&&(K||B||e)&&!p;!q||K||a.a||H.setTimeout(this.ba,3E3,r);var E=2;a.a=q?1:2;var U=(q?128:64)|(K?512:0);!k&&(v=this.a[m])&&(k=v.l)}k&&(b[101]=
k,b[128]=g);l&&(b[137]=l);!E||K||p||(A=this.Ga.bind(this,c,e));W(this,w,E||1,U||0,r,m,c,b,A)}}else d?(this.X(c,!0),delete this.g[c]):m!=q.u||q.L||p||(e?this.Ga(c,e,!0):mc(this,c))};function nc(a,b){var c=a.b[b];if(c&&c.ga){var d=c.b,e=c.a;P(a,7,2,c.L?128:c.o?256:c.g?512:0,[b,Math.round((c.h+d)*e),Math.round((c.G+d)*e),Math.round((c.width-d-c.s)*e),Math.round((c.height-d)*e)])}}
n.Ga=function(a,b,c){var d=this.g[a];if(d&&d.a){var e=d.port,f,h=256;2==d.a&&(null==c&&(f=this.b[e.a])&&(c=e.tabId==f.u&&!f.L),c?(h|=128,d.a=1):h|=64);(c=d.ha)&&!b&&(b=e.f);if(b){var k=b[0];var g=b[1];var l=b[2]||k+1;var m=b[3]||g+1;var r=b[4];if(b=!c&&e.f)k+=b[0],g+=b[1],l=Math.min(l+b[0],b[2]),m=Math.min(m+b[1],b[3]);if(e=this.a[e.tabId])var q=e.o}P(this,9,1,h,[a,k,g,l,m,r,q])}};
n.ba=function(a){var b=this.i,c=this.a,d=this.b,e=a?[d[a]]:V(d);a=[];d={};for(var f of e)!f||f.L||f.aa||b[f.u]||a.push(f.u);if(a.length)for(var h of V(this.g))h.a&&(b=h.port,f=b.tabId,a.includes(f)&&((f=b.B?b:c[f])&&f.update&&(f.update=!1,f.postMessage([14,!1])),h.b?b.B?b.postMessage([15,null,h.id]):hc(this,b,null,d):this.Ga(h.id,null,!0)))};function oc(a,b){var c=a.b,d;if(b=null==b?V(c):(d=c[b])?[d]:null)for(d of b)Bb(a,d.u,void 0)}
function Bb(a,b,c,d){d=0!=d;var e=c?0:2;c=c?32:64;for(var f of V(a.g))f.a&&f.port.tabId==b&&f.a!=e&&(d||f.b)&&(f.a=e,P(a,8,1,c,[f.id]))}function mc(a,b){var c=a.g[b];c&&1==c.a&&(c.a=2,P(a,8,1,64,[b]))}function pc(a,b,c,d){var e=a.Na,f=(e&b)!=((c?255:128)&b);a.Na=c?e|=b:e&=~b;f&&(c=a.c[-32],b=a.c[-33],c=a.Ma=0!=c&&(e&c)==c,e=a.Ta=0!=b&&(e&b)==b,a.pb=(c||e)&&d||null)}
n.bb=N[N.length]=function qc(a,b,c,d,e){var h=this.b[a];if(h)if(h.aa?d&&(H.clearTimeout(h.aa),h.aa=null):d||(d=-1),0<=d)h.i|=b,h.l|=c,d&&(h.aa=H.setTimeout(qc.bind(this),d,a));else{b|=h.i;c|=h.l;h.i=h.l=h.aa=null;if(b){for(var k of V(this.h))k.B&&k.a==a&&(k.update=!0);e?this.M(e):browser.windows.get(a,this.M);browser.tabs.query({windowId:a,active:!0},this.M)}if(c){if((a=this.b[a])&&!a.L&&!a.aa&&(a=a.u,!this.i[a])){b=this.g;for(var g in b)c=b[g],c.a&&c.port.tabId==a&&1==c.a&&P(this,8,1,1152,[g])}}else this.ba(a)}};
n.M=N[N.length]=function rc(a,b){browser.runtime.lastError;a instanceof Array&&(a=a.shift());if(a){var d=a.windowId||a.id,e=this.b[d];if(e){var f=!a.windowId;if(f){var h=b?e.a=this.Ra:e.a,k=e.g="minimized"==a.state,g=e.o="maximized"==a.state;k||(D?(e.width=Math.round(a.width/h),e.height=Math.round(a.height/h),e.c=Math.round(a.left/h),e.f=Math.round(a.top/h)):(e.width=a.width,e.height=a.height,e.c=a.left,e.f=a.top),k=e.L,a=e.L="fullscreen"==a.state,h=g&&-e.c,0<h&&16>=h&&h==-e.f&&(e.b=h),a==k||b||(a?
oc(this,d):this.ba(d)))}else{if(e.H&&Pa(a.url))return;a.active&&(e.u=a.id);a.width&&(e.D=a.width);a.height&&(e.v=a.height)}if(!e.g){h=e.width;k=e.D;g=e.height;a=e.v;var l=!F&&(k>h||a>g);if(l||!k||!a){f||l&&browser.windows.get(d,rc.bind(this));return}f=h-k;h=f/2;0<=h&&16>=h?(e.b=h,e.h=e.s=0):(h=e.b,F||ka?e.h=f-2*h:e.s=f-2*h);f=g-a-2*h;f>=(e.I?20:50)&&f<=ua&&(e.G=f);e.H=!0}b||nc(this,d);return e}}};function Ab(a,b){return a.i[b]?!0:(a=a.a[b])&&a.refresh?(a.refresh=!1,browser.tabs.reload(b),!0):!1}
n.Qc=function(a,b,c,d){a.j=b;a.m=c;a.refresh&&!d&&(a.refresh=!1);null==a.R&&this.kb(a);this.ba(a.a);0<this.v&&a.B&&1==a.O&&((a=this.c[11])&&a.test((new URL(b)).hostname)||gc(this))};n.Sc=function(a,b,c,d,e){a.l=b;a.o=e;a=[a.c,a.tabId,a.a,d,e];d={};d[110]=b;d[128]=c;P(this,21,1,0,a,d)};
n.Uc=function(a,b,c,d,e){var f=a.tabId,h=this.a[f+","+c];if(h){var k=h.f;h.qa=d;if(h.f=e){var g=a.f;g&&(e[0]+=g[0],e[1]+=g[1],e[2]=Math.min(e[2]+g[0],g[2]),e[3]=Math.min(e[3]+g[1],g[3]));if(k&&k.join()!=e.join()){k=this.a;a=a.tabId+",";c=a+c;for(var l in k)l.startsWith(a)&&(g=k[l],g.b==c&&h.postMessage([16,b,g.R,g.qa]))}}if(!this.i[f]){this.Ga(d,e);for(var m of V(this.g))m.port==h&&m.a&&m.b&&!m.ha&&h.postMessage([15,null,m.id])}}};
function hc(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],f;f=a[b.b];b=f){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(f)}for(f=e.pop();b=e.pop();f=b)d=b.qa,c[2]=b.R,c[3]=d,c[4]=d?null:b.j,c[5]=d?null:b.Z,f.postMessage(c)}function ic(a,b,c){a=a.a;b+=",";var d=0,e;for(e in a)e.startsWith(b)&&(a[e].postMessage(c),d++);return d}
n.Da=function(a,b){var c={file:"content.js",runAt:"document_start",matchAboutBlank:!0};!D&&b?c.frameId=b:c.allFrames=!0;if(a instanceof Array)for(;b=a.shift();)try{b.discarded||browser.tabs.executeScript(b.id,c,O)}catch(d){}else if(b=a)try{browser.tabs.executeScript(b.id||b,c,O)}catch(d){}};function sc(a,b,c,d){null==c&&(c=b.m==a.la);P(a,6,2,17|(c?2048:1024)|(b.o?256:b.g?512:0),[b.m,b.ga,b.width,b.height,b.c,b.f,b.a],{[117]:d})}
n.Kb=N[N.length]=function tc(a,b,c){if(b){a={};for(var e of c)a[e.windowId]=e;for(var f of b)e=a[f.id],b=this.M(f,!0)||this.Bb(f,!0,e),sc(this,b,f.focused,f.title||e&&e.title)}else{if(!a){try{browser.windows.getAll({windowTypes:["normal","popup","app"]},b=S())}catch(h){browser.windows.getAll(b)}browser.tabs.query({active:!0},c=S());return T(tc,this,1,b,c)}if(D&&1==a&&c){b=ec();for(e of c)browser.windows.get(e.windowId,b[b.length]=S());return T(tc,this,2,b,c)}}};
n.Pc=N[N.length]=function uc(a,b){if(void 0===a)return vc("system.display",uc.bind(this));if(a){if(!b)return browser.system.display.getInfo(null,uc.bind(this,a));this.Ib=b[0].displayZoomFactor}};
n.oc=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){a.name=a.name.split(":").shift();var c=a.id;null==c&&(c=a.id=this.Oc++);var d=b.id,e="top"==a.name;a.tabId=d;a.a=0>b.index?null:b.windowId;a.g=!0;a.h=!1;a.update=e;a.B=e;a.R=e?0:a.sender.frameId;a.s=0;a.j=a.sender.url||e&&b.url||null;a.Z=null;this.h[c]=a;e&&(this.a[d]=a);a.j&&(a.O=Sb(this,(new URL(a.j)).hostname));a.onMessage.addListener(this.pc.bind(this,a));a.onDisconnect.addListener(this.Ea);this.kb(a)}};
n.Ea=function(a,b){browser.runtime.lastError;if(a.g){a.g=!1;var c=a.tabId+","+a.R,d=this.pa,e=this.g,f,h=this.va,k=this.f,g,l;for(l in d)d[l].port===a&&delete d[l];for(l in e)if(f=e[l],f.port===a)this.X(l),delete e[l];for(var m in h)h[m]===a&&delete h[m];for(l in k)(g=k[l],g.port!==a||g.C)||delete k[l];this.pb===a&&pc(this,255,!1);delete this.h[a.id];delete this.a[c];a.B&&delete this.a[a.tabId];if(D&&!b)browser.tabs.executeScript(a.tabId,{code:"__idm_connect__ && __idm_connect__(); true;"},O);else for(l in a=
this.G,a)c==a[l].c&&delete a[l]}};
n.pc=function(a,b){var c=b.shift();b.unshift(a);switch(c){case 21:this.Qc.apply(this,b);break;case 24:this.Sc.apply(this,b);break;case 22:this.Uc.apply(this,b);break;case 23:this.Tc.apply(this,b);break;case 41:this.nc.apply(this,b);break;case 25:this.La.apply(this,b);break;case 26:xb(this,a.tabId,!0,!0,!1,a,b[1],b[2],b[3]);break;case 27:this.Gc.apply(this,b);break;case 28:this.X(4294967295);break;case 29:this.vb.apply(this,b);break;case 30:this.vb.apply(this,b);break;case 31:this.ic.apply(this,b);
break;case 32:this.lc.apply(this,b);break;case 39:this.jc.apply(this,b);break;case 33:this.cc.apply(this,b);break;case 34:this.hc.apply(this,b);break;case 35:this.kc.apply(this,b);break;case 36:this.Fc.apply(this,b);break;case 37:this.rc.apply(this,b)}};
n.xb=function(a){var b=a.type,c=a.m,d=a.flags,e=a.a,f;if(1==b){var h=e[0];if(f=this.za[h])b=f.type,delete this.za[h]}switch(b){case 3:0<=this.Aa&&(this.Aa=-1,this.gb());d=e[0];var k=e[5];f=e[6];c=e[4];var g=e[8];this.da=d;this.ub=9>d;this.ib=10<=d;wc(this,f);xc(this,k,a);yc(this);if(c||g)g=(c?c/96:1)*(g?g/100:1),this.Ra=C&&1.245>g?1:g,this.Kb(),C&&this.Ib&&this.Pc();Tb(this);break;case 4:g=this.c;this.o=!!(e[3]&2147483648);this.Ka=!!(e[3]&1073741824);xc(this,e[2],a);yc(this);d&2048&&(H.idm=this);
g[-6]=0<(d&64);g[-10]=0<(d&1024)||La;g[-5]=0<(d&32);g[-1]=0<(d&2);g[-8]=0<(d&256)||2>c;g[-9]=0<(d&512)||2>c;g[-32]=e[0];g[-33]=e[1];g[12]=a[12];g[17]=a[17];X(g,a,1);X(g,a,2);X(g,a,3);X(g,a,4);X(g,a,10);X(g,a,9,2);X(g,a,11,2);X(g,a,20);X(g,a,21,1);zc(g,a,19);zc(g,a,18,1,1);(this.N||this.jb)&&zb(this);break;case 18:g=e[0];e=e[1];d=gb[e?-e:g];if(!d)break;e=this.ea[g]={};f=d[2];e.O=g;e.Rb=d[0];e.Ob=d[1];for(k in a)(k=parseInt(k))&&(102==k||110<k&&150>k)&&(e[k]=f.includes(k)?RegExp(a[k]):a[k]);for(k of f)e[k]||
(e[k]=za);g=this.ea.map(Ac(102)).filter(aa);this.ob=RegExp("^https?://(?:"+g.join("|")+")","i");X(e,a,101,2);break;case 5:a=e[0];g=e[1];Bc(this,a,d,g);break;case 6:if(d&4)break;a=f.a[0];k=e[1];g=e[2];Bc(this,a,d,g,k);break;case 8:a=e[0];g=d&32;if(4294967295==a)ic(this,this.m,[13,!1]),this.m=null;else if(a=this.g[a])a.a=g?0:2;break;case 11:a=e[0];4294967295==a&&(xb(this,this.m,!0,!0),this.m=null);break;case 12:try{var l=a.a[5];g=4==l?2:3;if(1==l||2==l){if(Wb(this,a)){var m=a[4];if(this.c[3].test(m))1==
l?g=6:l=4;else if(this.c[-1]||this.c[4].test(m))g=6;a[8]|=256}if(3==g){var r=this.b[this.la];r&&this.i[r.u]&&(g=1)}}if(4!=l)W(this,a,g);else if(!this.ub||a.a[6]||a.a[7]){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.Hc(a)}else W(this,a,1)}catch(q){W(this,a,0)}break;case 13:a=f.a[0];d=f.a[5];e=e[1];k=3==e;if(3>=d)f.flags&128?kc(this,a,k):Y(this,a,k);else if(5==d)if(e){if(a=(d=this.f[a])&&d.ra){k=d.method;e=d.$;f=d.requestHeaders;e&&((e=Cc(e,f))?
e=new Blob(e):k="GET");a.timeout=1E4;a.onreadystatechange=this.qc.bind(this,a,d.id);a.open(k,d.url,!0);for(g of f)d=g.name,k=d.toLowerCase(),k.startsWith("x-idm-")||(Qa(k)&&(d="x-idm-"+d),a.setRequestHeader(d,g.value));a.send(e)}}else Dc(this,a);break;case 20:g=a[123];e=!g;a=[a.f];d={};F&&(k=this.ma)&&(d[122]=k,e||(e=k.substr(2).split(";",1).shift()==g));d[121]=this.s;P(this,1,2,e?2:4,a,d);break;case 24:this.Ic(a);break;case 22:this.Lb(e[0],e[1],a[131],a[130]);break;case 100:d&1&&P(this,100,1,0,[a.f],
a);break;default:d&1&&P(this,1,2,0,[a.f])}};n.Lb=N[N.length]=function Ec(a,b,c,d,e){if(!D&&null==va){if(void 0===e)return vc("notifications",Ec.bind(this,a,b,c,d));va=e||!1}va&&(browser.notifications.create(a.toString(),{type:"basic",title:d||"",message:c,iconUrl:"images/logo48.png"},O),b&&H.setTimeout(browser.notifications.clear,1E3*b,a.toString(),O))};
n.Ic=N[N.length]=function Fc(a,b,c){if(!b)return c=!!(a.flags&16),Q(a[6],Fc.bind(this,a,!0),c);b=browser.runtime.lastError||!c;a=[a.f,c?c.length:0];c={[51]:R(c)};P(this,1,2,b?4:2,a,c)};
n.Hc=N[N.length]=function Gc(a,b,c,d){try{var f=a.c||a.a[2],h=a.a[8],k=this.g[h];if(b)if(c)var g=this.h[c];else{if(d){var l=this.b[d.id];l&&(g=this.a[l.u])}}else if(k&&k.port)g=k.port;else if(f in this.h)g=this.h[f];else if(f=this.Qb(a,c=S()))g=this.h[f];else return browser.windows.getLastFocused(d=S()),T(Gc,this,a,!0,c,d);if(g)a.c=g.id;else return W(this,a,0);l=this.b[g.a];if(!l||!l.ga)return W(this,a,1);var m=this.a[g.tabId];m&&m.update&&(m.update=!1,m.postMessage([14,!0]));var r=Qb(this),q=[15,
r.a,h];r.H=a;h||q.push(a[6],a[17],a[50],a[31],a[133],a[134]);g.B||hc(this,g,r.a);g.postMessage(q)}catch(p){return W(this,a,0)}};function W(a,b,c,d,e,f,h,k,g){if(-1!=c){k||(k={});k[8]=b[8];a=l.bind(a,d|(0==c?4:2),[b.f,c,e,h,f,-1],k,g);b.flags&32&&(3==c||2==c)?Q(b[6],a,!!(b.flags&16)):a();function l(m,r,q,p,w){browser.runtime.lastError;w&&(r[5]=w.length,q[51]=R(w));P(this,1,2,m,r,q)&&p&&p()}}}n.mc=function(a){Ob(this,a).a=!0;F&&browser.windows.get(a.windowId,this.M)};
n.yb=function(a,b){var c=a.tabId,d=a.frameId,e=a.url,f=a.transitionType,h=a.frameType,k=a.documentId,g="prerender"==a.documentLifecycle;this.K!=c||Pa(e)||(this.K=null);d&&g&&"outermost_frame"==h&&(d=a.frameId=0);f=f?f.endsWith("_subframe"):D&&0<d;var l=!0;if(h=this.G[c+","+d]){l=h.g;h.g=g?k:null;if(l&&l==k)return;k=h.i;l=!(e&&k&&(new URL(e)).hostname==(new URL(k)).hostname);h.i=e}else g&&(h=Ob(this,a),h.g=k);!f&&this.i[c]&&vb(this,l,c);if(k=this.a[c+","+d])if(this.m&&(a=this.b[k.a])&&a.u==this.m&&
this.X(4294967295),b){a:{b=k.j;c=new URL(b);d=new URL(e);if(c.origin==d.origin&&c.pathname==d.pathname)switch(Sb(this,c.hostname)){case 1:if("/watch"==c.pathname&&c.a("v")==d.a("v")){b=!0;break a}break;case 4:if((c.pathname.startsWith("/p/")||c.pathname.startsWith("/reel/"))&&c.a("img_index")==d.a("img_index")){b=!0;break a}}b=e==b}if(!b){b=this.g;var m,r;for(r in b)if(m=b[r],m.port===k)2==k.O||4==k.O?mc(this,r):(this.X(r),delete b[r]);k.s++;k.j=e;k.B&&(k.update=!0);k.postMessage([17,!0])}}else this.Ea(k,
!0),f&&"about:blank"==k.j&&this.Da(c,d);else f&&"about:blank"==e?(Ob(this,a),this.Da(c,d)):h&&h.a&&(h.j||!b)?h.a=!1:F&&browser.tabs.get(c,this.M)};n.dc=function(a){return this.yb(a,!0)};
n.Bb=function(a,b,c){var d=a.id;c={m:d,width:a.width,height:a.height,c:a.left,f:a.top,a:this.Ra,b:8,G:ta,h:0,s:0,I:"popup"==a.type||"app"==a.type,L:"fullscreen"==a.state,o:"maximized"==a.state,g:"minimized"==a.state,u:c&&c.id,v:c&&c.height,D:c&&c.width,H:!F,ga:null,aa:null};Object.setPrototypeOf(c,qb.prototype);this.b[d]=c;a.focused&&(this.la=d);b?(browser.tabs.query({windowId:d,active:!0},this.M),browser.tabs.query({windowId:d,url:L},this.Rc),browser.tabs.query({windowId:d,url:L},this.Da)):F&&this.Ua==
d&&(this.Ua=null,browser.tabs.query({windowId:d,active:!0},this.M));return c};n.Rc=function(a){for(var b of a)Ob(this,0,b.id,!0,b.url)};n.Cb=function(a){P(this,5,1,32,[a]);delete this.b[a];this.J==a&&yb(this)};n.Ec=function(a){if(0<a){this.J&&browser.windows.update(this.J,{drawAttention:!0});var b=this.b[a];b&&(this.la=a,b.ga||sc(this,b,!0),browser.windows.onBoundsChanged||browser.windows.get(a,this.M),Ab(this,b.u),D&&this.bb(a,!1,!0,500))}else this.la=null};
n.Dc=function(a){this.bb(a.id,!0,!1,-1,a)};function Bc(a,b,c,d,e){var f=a.b[b];f?(d&&(f.a=d),e&&(f.ga=e),d=!!(c&128),f.L!=d&&(f.L=d)&&oc(a,b),(e||c&4096)&&nc(a,b)):a.Cb(b)}n.wc=function(a,b,c){var d=c.active;c=c.windowId;var e=d&&this.b[c];e&&(e.ga||sc(this,e));"complete"==b.status&&(a=this.a[a])&&!a.h&&(a.h=!0,d&&this.ba(c))};
n.vc=function(a){var b=this.a,c=this.G,d=a+",";this.K==a&&(this.K=null);var e=b[a];e&&this.Ea(e,!0);for(var f in b)f.startsWith(d)&&this.Ea(b[f],!0);for(var h in c)h.startsWith(d)&&delete c[h];delete this.i[a]};
n.tc=function(a){var b=a.tabId;a=a.windowId;this.Na=0;this.m&&this.X(4294967295);var c=this.b[a];c?(Bb(this,c.u),c.u=b,(c=this.K)&&b!=c&&(this.J?browser.windows.update(this.J,{drawAttention:!0}):this.l&&this.N&&(this.K=null,H.setTimeout(browser.tabs.remove,250,c))),browser.tabs.get(b,this.M),Ab(this,b)||this.ba(a)):F&&(this.Ua=a)};n.uc=function(a,b){b=b.newWindowId;for(var c of V(this.h))c.tabId==a&&(c.a=b);Bb(this,a,!0)};n.fc=function(a){this.J&&"idle"==a&&browser.windows.update(this.J,{focused:!0})};
n.vb=function(a,b,c){if(a.B){var d=a.tabId;a=a.a;var e=this.b[a];this.m&&this.X(4294967295);if(e&&e.u==d){var f=!1;b&&(e.D=b,f=!0);c&&(e.v=c,f=!0);Bb(this,d,!1,f);this.bb(a,f,!1,500)}}else a.qa&&(b=this.a[a.b])&&b.postMessage([16,null,a.R,a.qa])};n.ic=function(a,b,c){(b=hb[b])&&pc(this,b,c,a)};n.lc=function(a,b,c){0==b&&pc(this,128,c,a)};n.jc=function(a,b,c,d){this.Oa=a.id;a.Ub=b;a.fb=c;a.Vb=d};n.cc=function(){pc(this,255,!1)};
n.hc=function(a,b,c,d){var e=a.c;e&&(a=32,c=[e,null==c?(a|=16,-2):c],P(this,16,1,a,c,{[110]:b,[115]:d}))};n.Fc=function(a,b,c){if(a=this.f[b])P(this,16,1,48,[a.id,0],{[115]:c}),a.Ha=!1,a.mb&&Y(this,a)};n.rc=function(a,b,c,d){P(this,19,2,0,[b,c,a.tabId,a.c],d)};function Dc(a,b){if(b=a.f[b]){var c=b.ra;b.Ha=!1;b.ra=null;b.mb&&Y(a,b);c&&c.abort()}}n.qc=function(a,b){4==a.readyState&&(P(this,16,1,48,[b,0],{[115]:200==a.status?a.response:null}),Dc(this,b))};
function Hc(a,b){var c=a.c;if(b.Fa||a.i[b.tabId]||!c[-6])return 1;if(b.fa)return 6;if(b.W&&c[-1])return 1;var d=b.Ia,e=b.cb=jc(d.pathname);return c[9].test(d.hostname)||c[19].test(d.href)?1:2==(b.U&7)&&(b.Ya||c[-10])?d.pathname.endsWith("/")||c[21].test(d.pathname)?1:c[1].test(e)||a.o&&!c[20].test(e)?4:1:6}
function Ic(a,b){var c=!b.S;if(b.fa&&c)return 3;var d=a.c,e=d[18],f=d[1],h=b.Ia,k=b.cb,g=b.sa||(h.search?null:k),l=b.W,m=Ba.includes(b.type),r=!b.Ya,q=!m&&e.exec(h.href);if(q){var p=e.Vc,w=e.Wc,t=e.Xc,v=e.Yc;for(e=1;e<q.length;++e)if(q[e]){p=p[--e];if(null===p)break;q=0;if(p.includes("G")){var A=!0;q|="GET"==b.method}p.includes("P")&&(A=!0,q|="POST"==b.method);if(A&&!q)break;A=p.includes("V")|p.includes("A")|p.includes("C");p.includes("H")&&(b.sb=!0);if((A?b.sb:l?!p.includes("S"):p.includes("X"))||
r&&p.includes("D"))return 1;if(q=v[e]){q=q.exec(h.href);if(!q)break;h=w[e];if(w=h.F){var B=!0;var K=q[w]}if(w=h.T){B=!0;var E=q[w]}}E||(E=jc(K)||p.includes("T")&&(B=!0,k)||t[e]);if(A)return E&&(b.cb=E),l||(b.W=!0),b.S=!0,6;if(c&&(E?f.test(E):!B))return b.ab=16777216,4;break}}if(!c)return 6;if(g&&(m&&d[2].test(g)||l&&d[4].test(g)))return 1;if((F||a.ca)&&(b.Ya||d[-10])){if(l&&d[3].test(g))return 6;if((!l||a.o)&&g&&f.test(g))return b.ab=8,4}return 6}
function Jc(a,b){if(b.Tb)return a.ia(6,b),6;var c=b.statusCode;if(200!=c&&206!=c&&304!=c)return 1;var d=Z(b.responseHeaders,"Content-Type"),e=Z(b.responseHeaders,"Content-Disposition"),f=Kc(d).toLowerCase(),h="attachment"==Kc(e).toLowerCase();c=b.W;var k=b.ha;if(b.Sb=k&&!h&&"text/html"==f){if(b.C){var g=Pb(a,b);g&&(g.C=!0);a.ia(5,b)}return 1}if(c?b.Fa:b.S)return 1;if(a.o&&k&&h)return 4;var l,m,r=a.c,q=b.Ia,p=q.hostname,w=q.pathname,t=(e=Lc(e,"filename")||Lc(d,"name"))&&jc(e);if(e){if(!t&&!c)return 1;
if(t&&(!c||5>=t.length)){var v=Lc(d,"charset");var A=!v||"utf-8"==v||"utf8"==v;v=!0}}v||(e=w.split("/").pop(),(t=b.cb||jc(e))&&t.toLowerCase()==f.split("/").pop()&&(v=!0));if(!v){d=r[10].test(f);var B=jb[f];if(B)if(B=B.split("|"),t&&B.includes(t))v=!0;else if(c&&Ta(t))v=!0;else if(c?!d:!t){v=!0;var K=d;t=B[0]}!v&&t&&(h&&k?v=!0:d?v=K=!0:B||Sa(t)||(v=K=!0))}if(c){B=Sb(a,p);k=a.ea[B];d=w+q.search;switch(B){case 0:break;case 1:if(k[111].test(d)){var E=v=!0;t=null}else if(k[112].test(d))var U=!0;else if(k[115].test(d)&&
"application/json"==f)var pa=!0;else if(k[113].test(d)||k[114].test(d))var qa=!0;break;case 2:(p=k[111].exec(d))&&(Ra(f)||"text/html"==f)?(f=p[1]&&k[112].exec(b.port.j))&&p[1]!=f[1]||(qa=!0):k[114].test(d)?pa=!0:h&&"image"==b.type&&"MP4"==t&&(m=!0);break;case 3:"M4S"==t&&(v=!0);p==k[111]&&k[112].test(w)&&Ra(f)&&(qa=!0);break;case 4:k[111].test(d)&&Ra(f)&&(pa=!0);break;case 5:k[111].test(d)&&"text/html"==f&&(pa=!0);break;case 6:k[111].test(d)&&(qa=!0);break;default:k[111].test(w)&&(pa=!0)}v&&("M3U8"==
t||"F4M"==t||a.ib&&"MPD"==t?qa=!0:"F4F"==t&&(e.endsWith("Seg1-Frag1")||e.endsWith("Seg1-Frag2")||e.includes("Seg1-Frag2_"))&&(l=!0));"ASF"==t&&((f=Z(b.responseHeaders,"Content-Length"))&&102400>=parseInt(f)&&(m=!0),"DCLK-AdSvr"==Z(b.responseHeaders,"Server")&&(m=!0))}if(m)return 1;v&&(c&&r[3].test(t)?E=!0:c&&r[4].test(t)?b.S=!0:!b.S&&r[1].test(t)&&(g=!0));if(E){var Ub,Vb;if(b.sb)E=!1;else if(m=r[11])m.test(q.hostname)?E=!1:(Ub=a.a[b.tabId])&&(Vb=Ub.j)&&m.test((new URL(Vb)).hostname)&&(E=!1)}if(pa)U=
b.Ha=!0;else if(qa||l)"POST"!=b.method||b.$?(a=new XMLHttpRequest,a.responseType=l?"blob":"text",b.ra=a,U=!0):U=!1;if(!g&&!E&&!U)return 1;v&&(b.sa=t);A&&(b.fileName=e);b.C|=U;b.ab=E||U?256:16|(c?4096:0)|(K?8388608:0);return g?4:E?2:5}
n.ia=N[N.length]=function Mc(a,b,c,d,e,f){var k=b.url,g=b.U||cc(k),l=1==(g&7),m=b.requestHeaders;if(l&&!m&&!d)if(e)f=R(f);else if(f=Z(m,"Cookie"),null==f)return Q(k,Mc.bind(this,a,b,c,d,!0)),!0;var r=b.id,q=b.port&&b.port.id;e=b.timeStamp;var p=c?y(c.timeStamp-e):null,w=b.ab,t=b.responseHeaders,v=b.Db,A=c&&c.ip;c=0;3==(A?A.length-A.ja(".","").length:0)?w|=33554432:2<(A?A.length-A.ja(":","").length:0)&&(w|=4194304);g&16&&(w|=2097152);"POST"==b.method&&(w|=512);4>a&&(F||d)&&(c|=1);b.C&&b.ra&&(c|=1);
b.C&&5!=a&&(c|=32);b.W&&(c|=16);b.Xa&&(c|=8192);b.ha&&(c|=b.B?2048:4096);a=[r,q,y(e),b.statusCode,g&7,a,b.tabId,b.frameId];k={[6]:Zb(k,l,this),[12]:b.statusLine,[17]:b.Z,[4]:b.sa,[100]:b.fileName,[127]:b.bd,[129]:p,[122]:this.s,[8]:w,[11]:Nc(m),[13]:Nc(t),[18]:Nc(v)};b.$&&(k[14]=Cc(b.$,m));b.$a&&(k[19]=Cc(b.$a,v));if(!m){l=this.G;g=b.tabId+","+b.frameId;do g=(p=l[g])&&p.c,p=p&&p.j,"about:blank"==p&&(p=null);while(!p&&g);k[50]=p;k[51]=f;k[54]=navigator.userAgent}F&&(k[122]=Lb(this,b.proxyInfo,Z(m,
"Proxy-Authorization")),k[55]=Lb(this,b.Eb,Z(v,"Proxy-Authorization")));if(!b.Sb||!b.B)if(b=this.a[b.tabId])k[7]=b.j;16>this.da&&(a[2]=y(e/1E3),a[3]=y(e%1E3*1E3));return!!P(this,13,1,c,a,k,d)};
n.ta=N[N.length]=function Oc(a,b,c,d,e){if(0==a)b.resolve=d,b.reject=e,Nb(this,b);else{d=this.ca?new XMLHttpRequest:null;e=this.ia(a,b,c,d);d&&(e=(d=e&&parseInt(d.getResponseHeader("x-idm-status")))?3==d:this.ia(a,b,c));if(e)return Ma&&!c?void(b.Wa=!0):F?new Promise(Oc.bind(this,0,b,null)):Y(this,b,!0);b.S=!0}};
function Y(a,b,c){var d=a.f,e;if(!u(b))if(b=d[b])void 0;else return;var f=b.id,h=0<b.statusCode;if(c){if(b.ha||b.Xa){h=h||!b.requestHeaders;var k=Pb(a,b);k&&k.a&&b.B?browser.tabs.remove(b.tabId):C&&h&&!b.Xa?e={redirectUrl:"javascript:void(0)"}:D&&h?e={redirectUrl:Pc(b,k)}:Oa&&h&&(e={redirectUrl:a.V||Pc(b,k)})}e||(e={cancel:!0});b.Wa=!0}(a=b.resolve)&&void 0!==c&&(b.resolve=b.reject=null,a(e||{}));if(c=b.reject)b.resolve=b.reject=null,c();if(b.ra||b.Ha)return b.mb=!0,e;delete d[f];F&&delete d[b.Ja];
D&&delete d[b.requestId];b.Jb&&delete d[b.Jb];return e}n.xc=function(a){var b=new URL(a.url);if(b.search.startsWith("?d=")){var c=this.a[a.tabId];this.ka("idmreg:"+b.href.substr(b.protocol.length),null,c&&c.j);Y(this,a.requestId);(b=Pb(this,a))&&b.a&&"main_frame"==a.type&&browser.tabs.remove(a.tabId);return{redirectUrl:Ha+"register=1"}}};n.Yb=function(a){if(!(0>a.tabId||a.initiator==Ja||this.Ka||(D||Oa)&&a.url.startsWith(Ha)&&a.type.endsWith("_frame")||a.url.startsWith(Ia)&&"main_frame"==a.type))return{cancel:!0}};
n.Ab=function(a){var b=a.type,c=a.tabId,d=a.frameId;if(!ra||Ca.includes(b))if(!(0>c&&0==d)||F&&a.originUrl!=Ka){var e=a.url,f=a.method,h=cc(e);if(h&&("GET"==f||"POST"==f)&&e!=this.V){d&&"outermost_frame"==a.frameType&&(d=a.frameId=0);var k=a.id=D?String(this.Zc++):a.requestId,g=this.f[k],l=this.Ta,m="POST"==f,r="image"==b,q=C&&"other"==b,p=!q&&0>c&&(F||0>d),w=0<c&&b.endsWith("_frame"),t=p?null:this.a[c+","+d];if(t||w||p||q||g){F&&m&&g&&$a(g.statusCode)&&(f=a.method="GET",m=!1);w&&Ob(this,a,null,!1);
if(!l&&m&&a.requestBody){m=a.requestBody;var v=m.raw;if(v)for(var A=0;A<v.length&&(v[A].bytes||(v=null));A++);if(!(v||m.formData||C&&m.error))return}if((m=this.Oa)&&(v=t?t.id==m&&t:this.h[m])&&e==v.fb){q=v.Ub;if(m=v.Vb)a.fileName=m,a.sa=jc(m);t||(t=v);this.Oa=null}m=new URL(e);m.hash="";a.Ia=m;a.U=h;a.fa=this.Ma;a.Fa=l;a.B=w&&"main_frame"==b;a.ha=w;a.Xa=q;a.Nb=p;a.W=p||J.includes(b);a.S=r;a.C=this.ob.test(e);a.$=a.requestBody;a.port=t;a.Ya=h&8||(F?a.proxyInfo&&"https"==a.proxyInfo.type:this.Ca[h]);
0>c&&(a.tabId=null);0>d&&(a.frameId=null);if(g)a.id=g.id,a.port=t=g.port,a.fa=g.fa,a.Fa=g.Fa,a.Z=g.Z||g.url,a.Db=g.Db||g.requestHeaders,a.$a=g.$a||g.$,F&&(a.Eb=g.Eb||g.proxyInfo);else if(F&&p)for(var B of V(this.f))if(B.$c&&!B.Ja&&e==B.url&&b==B.type&&f==B.method){a=B;a.Ja=k;break}if(a.W&&!r){b=this.va;c=b.Jc;d=c.indexOf(e);if(0<=d)c.splice(d,1);else for(;30<=c.length;)delete b[c.shift()];b[e]=t;c.push(e)}switch(a.action=Hc(this,a)){case 1:a.S=!0;case 6:Nb(this,a);break;case 4:return this.ta(1,a)}}}}};
n.zc=function(a){var b=this.f[a.requestId];if(b){var c=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.Wa){if(b.Nb&&!b.port&&(a=Z(c,"Referer")))for(var d of V(this.h))if(d.j==a){b.port=d;break}F&&b.proxyInfo&&Lb(this,b.proxyInfo,Z(c,"Proxy-Authorization"),!0);d=b.Ia;if(!("POST"!=b.method||b.$&&!(b.$.error&&0<Z(c,"Content-Length"))||D&&1==Sb(this,d.hostname)&&this.ea[1][115].test(d.pathname+d.search)))return Y(this,b);switch(b.action=Ic(this,b)){case 1:b.S=!0;break;case 4:return this.ta(1,
b);case 3:return this.ta(3,b)}if(b.port&&b.port.C&&"xmlhttprequest"==b.type)for(d=0;d<c.length;d++){a=c[d];var e;if("accept"==a.name.toLowerCase()&&(e=Wa(a.value))){var f=b.Jb=e[3];this.f[f]=b;e[1]||e[4]?a.value=e[1]+(e[4]&&e[2]||"")+e[4]:c.splice(d--,1);return{requestHeaders:c}}}}}else if(0>a.tabId&&"xmlhttprequest"==a.type&&(a.initiator?a.initiator==Ja:a.originUrl?a.originUrl==Ka:1)){b=a.requestHeaders;c={};e=!1;for(d=0;d<b.length;d++)a=b[d],f=a.name.toLowerCase(),f.startsWith("x-idm-")?c[f.substr(6)]=
e=!0:"origin"==f&&a.value==Ja&&(c[f]=e=!0);if(e){for(d=0;d<b.length;d++)a=b[d],f=a.name.toLowerCase(),c[f]?b.splice(d--,1):f.startsWith("x-idm-")&&(a.name=a.name.substr(6));return{requestHeaders:b}}}};n.yc=function(a){if(!a.statusCode&&a.redirectUrl==a.url){a=a.requestId;var b=this.f[a],c=b&&Pb(this,b);c&&!b.statusCode&&c.f==a&&(b.$c=!0)}};
n.Bc=function(a){var b=this.f[a.requestId];if(b){var c=b.statusLine=a.statusLine,d=b.statusCode=a.statusCode||parseInt(c.split(" ",2).pop());if(b.Wa||204==d&&c.includes(" IDM "))return Y(this,b,!0);c=b.responseHeaders=a.responseHeaders;b.Tb=Za(d);if("image"==b.type&&(d=Z(c,"Content-Type"))&&d.toLowerCase().startsWith("image"))return Y(this,b);"quic"==Z(c,"Client-Protocol")?b.U|=16:(d=Z(c,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=Z(c,"Transfer-Encoding")&&(b.U|=16);switch(b.action=
Jc(this,b)){case 1:return Y(this,b);case 4:return this.ta(2,b,a);case 3:return this.ta(3,b,a)}if(b.Ha)return c||(c=[]),c.push({name:"x-idm-request-id",value:b.id.toString()}),{responseHeaders:c}}};n.Cc=function(a){var b=this.f[a.requestId];if(a.type.endsWith("_frame")&&(200==a.statusCode||304==a.statusCode)){var c=Pb(this,a);c&&(c.j=a.url,c.Z=c.l)}b&&(2==b.action?this.ia(4,b,a):5==b.action&&this.ia(5,b,a),Y(this,b))};n.Ac=function(a){Y(this,a.requestId)};
n.Kc=N[N.length]=function Qc(a,b,c,d){if(a){this.Gb=b.version;this.ya=b.silent;this.P=b.lastupt;this.nb=d;F&&(this.N=!!b.consent);this.P>Date.now()&&(this.P=null);b=b.client;if(c)for(var f of c)switch(f.name){case "idmwebext_cid":var h=parseInt(f.value);break;case "idmmzcc3_uri":this.jb=f.value==Ja}wc(this,null,b,h);this.Qa()}else c={url:I.homepage_url},oa&&(c.firstPartyDomain=null),browser.storage.local.get(null,b=S()),browser.cookies.getAll(c,c=S()),(F?1124073472<=G:D?1073741824<=G:1)&&browser.extension.isAllowedIncognitoAccess(d=
S()),T(Qc,this,!0,b,c,d)};function wc(a,b,c,d){a.da&&92>a.da?10<a.I&&(browser.storage.local.remove("client"),browser.cookies.remove({url:I.homepage_url,name:"idmwebext_cid"})):(b||(b=c||d))&&b!=a.I&&(a.I=b,c||browser.storage.local.set({client:b}),d||browser.cookies.set({url:I.homepage_url,name:"idmwebext_cid",value:String(b),expirationDate:2147483647}))}
function Tb(a){function b(l){l&&(this.K=l.id)}a.K&&(browser.tabs.remove(a.K),a.K=null);if(a.Hb||!a.N){var c=!a.l,d=!a.nb,e=!a.N,f=a.Ba,h=a.oa,k=a.Gb,g=a.Va;if(c){if(a.xa&&a.ya)return}else a.Hb=!1,g!=k&&(g&&browser.storage.local.set({version:g}),F&&browser.cookies.set({url:I.homepage_url,name:"idmmzcc3_uri",value:Ja,expirationDate:2147483647})),a.ya&&(a.ya=!1,browser.storage.local.set({silent:!1}));if(null!=k&&(e=!1,a.N=!0,g!=k?h&&k&&!f&&!e:!e))return;g=Ia+"current="+escape(g);k&&(g+="&previous="+
escape(k));h&&(g+="&manager="+(h?[h>>24&255,h>>16&255,h>>8&255,h&255].join("."):""));c&&(g+="&error=1");d&&(g+="&incognito=1");f&&(g+="&update=1");e&&(g+="&consent=1");F&&(g+="&mzffox=1");ka&&(g+="&opera=1");if(D||ja)g+="&msedge=1";if(e&&!c){browser.idle&&a.A(5,browser.idle.onStateChanged,a.fc)&&browser.idle.setDetectionInterval(15);browser.windows.create({type:"popup",width:Math.min(Math.round(.85*screen.availWidth),1100),height:Math.min(Math.round(.85*screen.availHeight),900),url:g},l.bind(a));
function l(m){m&&m.id?(this.J=m.id,this.K=m.tabs[0].id,vb(this,!1,null,!0)):yb(this)}}else browser.tabs.create({url:g},b.bind(a))}}function xc(a,b,c){null==b&&(b=Ya(c[13]))&&(b=b[1]<<24|b[2]<<16|b[3]<<8);a.oa=b>>>0}function yc(a){a.Ba=103417600>a.oa;a.v=103424E3>a.oa?Date.now():null;103424E3>a.oa?a.v=a.P?a.P+6E4*y(240*z()+480):Date.now():(a.v=a.P=null,browser.storage.local.remove("lastupt"))}
function gc(a,b){var c=Date.now();if(c>a.v||b&&!a.Ba)browser.storage.local.set({lastupt:a.P=c}),0<a.v&&(a.v=c+6E4*y(240*z()+480)),c="idmdwnlmfv4://idmreg://"+z().toString(36).substr(2),b?a.ka(c):H.setTimeout(a.ka,y(5E3*z()+5E3),c)}function fc(a,b){b=browser.i18n.getMessage(b);F?browser.tabs.executeScript(a,{code:'window.alert(unescape("'+escape(b)+'")); true;'},O):window.alert(b)}
n.A=function(a,b,c){if(null==b)return!1;var d=da(arguments);if(F||D)d[2]=function(){return c.apply(null,arguments)};this.eb.push(d);b.addListener.apply(b,d.slice(2));return!0};n.Pa=function(){for(var a=arguments.length?da(arguments):null,b=this.eb,c=0;c<b.length;c++)if(!a||a.includes(b[c][0])){var d=b.splice(c--,1).pop(),e=d.splice(0,2).pop();D&&d.splice(1);e.removeListener.apply(e,d)}};function S(){function a(b){browser.runtime.lastError;a.a?a.a(b):a.c=b;a.b=!0}return a}S.prototype=Object.create(Function.prototype);
function ec(){var a=[];Object.setPrototypeOf(a,ec.prototype);return a}ec.prototype=Object.create(Array.prototype);
function T(a,b,c){if(this instanceof T){c instanceof Array||(c=fa(arguments,2));for(var d=0,e=0,f=Function.prototype.bind.bind(this.g,this),h=0;h<c.length;h++){var k=c[h];if(k instanceof Function)k.b?(c[h]=k.c,e++):(k.a=f(h,null),d++);else if(k instanceof ec)for(var g=0;g<k.length;g++){var l=k[g];l.b?(k[g]=l.c,e++):(l.a=f(h,g),d++)}}d?(this.c=a,this.f=b,this.a=c,this.b=d):a.apply(b,c)}else return(new T(a,b,fa(arguments,2))).b}
T.prototype.g=function(a,b,c){var d=this.a;if(null===b)for(var e=2;e<arguments.length;e++)d[a++]=arguments[e];else d[a][b]=c;0==--this.b&&(this.c.apply(this.f,d),delete this.c,delete this.f,delete this.a)};function Ib(a){return browser.i18n.getMessage(a)||a}function Zb(a,b,c){var d=a.lastIndexOf("#");d>a.indexOf("?")&&"!"!=a[d+1]&&(a=a.substr(0,d));b&&c.Ba&&!a.startsWith("idmdwnlmfv")&&!Ua(a)&&(a="idmdwnlmfv4://"+a);return a}
function Pc(a,b){var c=a.port;b=b&&!b.h;var d=new URL(c&&c.j||a.url);D&&(c&&a.url==c.fb||(b=!1));return Ha+(b?"back=1":"host="+d.hostname)}function cc(a,b){a=a.split(":",1).shift().toLowerCase();a=ib[a]||0;return b?a&7:a}function jc(a){return(a=Xa(a))?a[1].toUpperCase():""}function Q(a,b,c){if(D&&a.startsWith("ftp:"))return b([]);a={url:a};c&&(a.session=!1);oa&&(a.firstPartyDomain=null);browser.cookies.getAll(a,b)}
function R(a){if(!u(a))return a;var b=[],c;for(c of a)b.length&&b.push("; "),b.push(c.name,"=",c.value);return b.join("")}function Nc(a){if(!a||!a.length)return null;var b=[],c;for(c of a)b.push(c.name,": "),null!=c.value?b.push(c.value):c.binaryValue&&b.push(new Uint8Array(c.binaryValue)),b.push("\r\n");return b}function Z(a,b){if(!a)return null;b=b.toLowerCase();for(var c of a)if(c.name.toLowerCase()==b){if(null!=c.value)return c.value;if(c.binaryValue)return ia(c.binaryValue)}return null}
function Lc(a,b){if(!a)return null;var c;a=a.split(";");for(b=b.toLowerCase();a.length;){var d=a.shift();var e=d.indexOf("=");if(0<e){var f=d.slice(0,e).trim().toLowerCase(),h=f.endsWith("*");if(h)f=f.slice(0,-1).trimRight();else if(k)continue;if(f==b){f=d.substr(e+1).trim();d=f.length-1;if('"'==f[0]?'"'==f[d]:"'"==f[0]&&"'"==f[d])f=f.slice(1,d);if(h&&f.includes("'")){if(f=f.split("'",3),h=f.shift().toLowerCase(),f=f.pop(),((d="utf-8"==h||"utf8"==h)||!k)&&(c=Rc(f))){var k=h;if(d)break}}else c=Rc(f)}}else 0>
e&&null==c&&d.trim().toLowerCase()==b&&(c="")}return c}function Kc(a){const b=/[;,]/;return a&&(a=a.split(b,1).shift().trim())&&!a.includes("=")&&Rc(a)||""}function Rc(a){try{return a&&decodeURIComponent(a)}catch(b){return unescape(a)}}
function Cc(a,b){var c,d=[];if(c=a.raw)for(var e of c){var f=e.bytes;if(f)d.push(f);else return null}else if(a=a.formData)if(b=ca(b)?Z(b,"Content-Type"):b,(c=Kc(b).toLowerCase())&&"application/x-www-form-urlencoded"!=c)if("multipart/form-data"==c){(b=Lc(b,"boundary"))||(b="----WebKitFormBoundary"+z().toString(36).substr(2));for(h in a)for(f of a[h])d.push("--",b,'\r\nContent-Disposition: form-data; name="',h,'"\r\n\r\n',f||"","\r\n");d.push("--",b,"--\r\n")}else return null;else for(var h in a){b=
encodeURIComponent(h).ja("%20","+");for(f of a[h])f=f instanceof ArrayBuffer?escape(ia(new Uint8Array(f))):null==f?"":encodeURIComponent(f),d.length&&d.push("&"),d.push(b,"=",f&&f.ja("%20","+"))}else return null;return d.length?d:null}function lb(a){for(var b=a.length,c=b,d=0;d<c;){var e=a.charCodeAt(d++);128<=e&&(2048<=e?(b+=2,e-55296&64512||d++):b++)}return b}
function Sc(a,b,c,d,e){browser.runtime.lastError;if(!a){ja&&Tc();D||browser.runtime.getPlatformInfo(b=S());navigator.userAgentData?navigator.userAgentData.getHighEntropyValues(["fullVersionList","uaFullVersion"]).then(c=S()):browser.runtime.getBrowserInfo&&browser.runtime.getBrowserInfo(c=S());try{browser.privacy&&browser.privacy.websites.firstPartyIsolate.get({},d=S())}catch(l){d=null}C&&browser.management.get("clhiejnehegdfknplplojohghjaklbae",e=S());return T(Sc,null,!0,b,c,d,e)}if(b&&"win"!=b.os)return Cb(!1);
a=navigator.userAgent;var f=a.match(/\s(?!(?:Chrome|Firefox|Gecko|Safari)\/)([A-Z]\w+)(?:\/(\d+(?:\.\d+){0,3}))?\b(?!.*\)\s+\S)/),h=a.match(/\s(Chrome|Firefox)\/(\d+(?:\.\d+){0,3})\b/);a=h?h[1]:"UNKNOWN";b=f?f[1]:a;h=h&&h[2]||"0.0";f=f&&f[2]||h;F&&(a="Mozilla");C&&navigator.brave&&(b="Brave");C&&e&&(b="Epic",sa=!0);if(u(c)){if(e=c.uaFullVersion)f=e;if(e=c.fullVersionList)for(var k of e){if(e=k.version)switch(k.brand){case "Chromium":a="Chrome";parseInt(e)==parseInt(h)?h=e:(b="UNKNOWN",f=e);break;
case b:f=e}}else if(e=c.version)if(53<=parseInt(e)&&(h=e),e=c.name)b=e}e=h.split(/\D+/);G=(e[0]<<24|e[1]<<22|e[2]<<8|e[3])>>>0;ma=a+"/"+h;na=b+"/"+f;F&&u(d)&&(oa=d.value);F&&939524096>G&&(Oa=!0);c=browser.webRequest.ResourceType;if(c){if(c.MEDIA){Ca.push("media");J.push("media");var g=!0}if(c.OBJECT_SUBREQUEST||(ra=F&&922746880>G))Ca.push("object_subrequest"),J.push("object_subrequest")}C&&(g||J.push("other"));F&&922746880>G&&J.push("other");D&&(Ca.push("fetch"),J.push("fetch"));new M;Uc(1,"debug.js");
Uc(2,"document.js")}function Tc(){var a="llbjbkhnmlidjebalopleeepgdfgcpec"==browser.runtime.id&&"ngpampappnmepgilojfohadhhmbhlaek";browser.management.get(a||"llbjbkhnmlidjebalopleeepgdfgcpec",function(b){browser.runtime.lastError;b&&b.enabled&&browser.management.setEnabled(a||browser.runtime.id,!1)})}
function Uc(a,b,c){c?4==c.readyState&&(fb[a]=btoa(c.responseText)):(c=new XMLHttpRequest,c.responseType="text",c.onreadystatechange=Uc.bind(null,a,b,c),c.open("GET",browser.runtime.getURL(b)),c.send())}
function X(a,b,c,d){if(b=b[c]||void 0){b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\.");b=1==d?b.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):3==d?b.replace(/(?<![*?])\*(?!\*)/g,"[^/]*").replace(/\?\*/g,"\\?.*").replace(/\*\*/g,".*?"):b.replace(/\?/g,".").replace(/\*/g,".*?");2==d&&(b=b.replace(/(^|\|)([^|]+?)~/g,"$1(?:$2\\.)?").replace(/(^|\|)~/g,"$1(?:.*?\\.)?"));b="^(?:"+b+")$";try{b=RegExp(b,1==d?"":"i")}catch(e){b=null}}a[c]=b||za}
function zc(a,b,c,d,e){b=b[c];var f=[],h=[],k=[],g=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)|\*+(?=\*)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(d){for(var l=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");l.length;){var m=l.shift();f.push(Va(m)?m:null);h.push(l.shift())}b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(e){l=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,
"$1").split("|");m=/<([A-Z]):(.*?)>/g;for(var r={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"},q,p=0;l.length;++p)if(q=l.shift()){for(var w={},t=["^"],v="",A,B=1;A=m.exec(q);++B)w[A[1]]=B++,v=RegExp.rightContext,t.push(RegExp.leftContext,"(",A[2].replace(/\*/g,r[A[1]]||".%%?"),")");t.push(v,"$");k[p]=w;g[p]=RegExp(t.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(m,"(?:$2)")}b=b.replace(/\*/g,".*?").replace(/%%/g,"*");b=d||e?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(K){b=
null}a[c]=b||(b=/(?!)/);d&&(b.Vc=f,b.Xc=h);e&&(b.Wc=k,b.Yc=g)}function mb(a){return ia(a instanceof ArrayBuffer?new Uint8Array(a):a)}function ac(a){return u(a)?a.source.ja("\\/","/"):a}function vc(a,b){b&&browser.runtime.lastError||browser.permissions.request({permissions:[a]},b)}function O(a){browser.runtime.lastError;a;!0}
URL.prototype.a="searchParams"in URL.prototype?function(a){return this.searchParams.get(a)}:function Vc(a){var c=Vc.cache||(Vc.cache={});return(a=(c[a]||(c[a]=new RegExp("[?&]"+escape(a)+"\\b(?:=([^&]*))?"))).exec(this.search))&&unescape(a[1]||"")};const $b=Function.bind.bind(function(a){return this[a]}),Ac=Function.bind.bind(function(a){return a&&a[this]});var V=Object.values;V||(V=function(a){return Object.keys(a).map($b(a))});
Array.prototype.fill||(Array.prototype.fill=function(a){for(var b=this.length;b--;this[b]=a);return this});String.prototype.ja||(String.prototype.ja=function(a,b){return this.split(a).join(b)});
const Hb=[[!0,-8,"menu_download_link","link,image,video",M.prototype.Sa],[!0,-8,"menu_download_link","page,frame,editable",M.prototype.Sa,Fa],[!0,-8,"menu_download_selected","selection",M.prototype.hb],[!0,-9,"menu_download_all","page,frame,editable",M.prototype.hb],[C,-8,"menu_download_item","link",M.prototype.Sa,["chrome://downloads/*"]]],Db=Ib("tooltip_title"),Fb=Ib("tooltip_disabled"),Gb=Ib("tooltip_error"),Eb="\n"+Ib("tooltip_text");N.splice(0);Sc();
